version: "3.9"

x-default-env: &default-env
  TZ: "${TZ:-UTC}"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: assistant-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - ../data/assistant/qdrant:/qdrant/storage

  llama-server:
    image: ghcr.io/ggerganov/llama.cpp:server
    container_name: assistant-llama-server
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ../data/assistant/models:/models
    environment:
      <<: *default-env
    command: >-
      --host 0.0.0.0
      --port 8080
      --model ${ASSISTANT_MODEL_PATH:-/models/llama3-8b-q4_k_m.gguf}
      --n-gpu-layers ${ASSISTANT_GPU_LAYERS:-32}
      --ctx-size ${ASSISTANT_CTX_SIZE:-4096}

  assistant-api:
    build:
      context: ../../../services/assistant/api
    container_name: assistant-api
    restart: unless-stopped
    ports:
      - "7070:7070"
    environment:
      <<: *default-env
      QDRANT_URL: "http://qdrant:6333"
      QDRANT_COLLECTION: "${ASSISTANT_COLLECTION:-homeauto-assistant}"
      EMBED_MODEL: "${ASSISTANT_EMBED_MODEL:-sentence-transformers/all-MiniLM-L6-v2}"
      LLM_URL: "http://llama-server:8080/v1/chat/completions"
      COLLECTION_TAG: "${ASSISTANT_COLLECTION_TAG:-homeauto}"
    depends_on:
      - qdrant
      - llama-server

  assistant-ingest:
    build:
      context: ../../../services/assistant/ingest
    container_name: assistant-ingest
    environment:
      <<: *default-env
      QDRANT_URL: "http://qdrant:6333"
      QDRANT_COLLECTION: "${ASSISTANT_COLLECTION:-homeauto-assistant}"
      EMBED_MODEL: "${ASSISTANT_EMBED_MODEL:-sentence-transformers/all-MiniLM-L6-v2}"
      ASSISTANT_DATA_ROOTS: "${ASSISTANT_DATA_ROOTS:-}"
    volumes:
      - ../../../config/assistant:/config/assistant:ro
      - ../../../docs:/data/docs:ro
      - ../../../config:/data/config:ro
      - ../../../scripts:/data/scripts:ro
      - ../../../flows:/data/flows:ro
    command: ["python", "/app/ingest.py"]
    depends_on:
      - qdrant

volumes: {}
